name: Destroy terraform resources on the given folder

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory with resources to be destroyed'
        required: true

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    destroy:
        name: 'terraform destroy'
        runs-on: ubuntu-latest    
        defaults:
            run:
              shell: bash
              working-directory: 'enviroments/production'
    
        steps:
        - name: Checkout
          uses: actions/checkout@v3
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.4.2
    
        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
    
        - name: Terraform Init
          id: init
          run: terraform init
        
        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Destroy
          run: terraform destroy -auto-approve